// FFI declarations for MPFR

/*
  Source: mpfr.h
  Version: 4.1.0.3
  Documentation: https://www.mpfr.org/
*/

use @mpfr_get_version[Pointer[U8]]()
use @mpfr_get_patches[Pointer[U8]]()
use @mpfr_buildopt_tls_p[I32]()
use @mpfr_buildopt_float128_p[I32]()
use @mpfr_buildopt_decimal_p[I32]()
use @mpfr_buildopt_gmpinternals_p[I32]()
use @mpfr_buildopt_sharedcache_p[I32]()
use @mpfr_buildopt_tune_case[Pointer[U8]]()
use @mpfr_get_emin[I64]()
use @mpfr_set_emin[I32](parg0: I64)
use @mpfr_get_emin_min[I64]()
use @mpfr_get_emin_max[I64]()
use @mpfr_get_emax[I64]()
use @mpfr_set_emax[I32](parg0: I64)
use @mpfr_get_emax_min[I64]()
use @mpfr_get_emax_max[I64]()
use @mpfr_set_default_rounding_mode[None](parg0: I32)
use @mpfr_get_default_rounding_mode[I32]()
use @mpfr_print_rnd_mode[Pointer[U8]](parg0: I32)
use @mpfr_clear_flags[None]()
use @mpfr_clear_underflow[None]()
use @mpfr_clear_overflow[None]()
use @mpfr_clear_divby0[None]()
use @mpfr_clear_nanflag[None]()
use @mpfr_clear_inexflag[None]()
use @mpfr_clear_erangeflag[None]()
use @mpfr_set_underflow[None]()
use @mpfr_set_overflow[None]()
use @mpfr_set_divby0[None]()
use @mpfr_set_nanflag[None]()
use @mpfr_set_inexflag[None]()
use @mpfr_set_erangeflag[None]()
use @mpfr_underflow_p[I32]()
use @mpfr_overflow_p[I32]()
use @mpfr_divby0_p[I32]()
use @mpfr_nanflag_p[I32]()
use @mpfr_inexflag_p[I32]()
use @mpfr_erangeflag_p[I32]()
use @mpfr_flags_clear[None](parg0: U32)
use @mpfr_flags_set[None](parg0: U32)
use @mpfr_flags_test[U32](parg0: U32)
use @mpfr_flags_save[U32]()
use @mpfr_flags_restore[None](parg0: U32, parg1: U32)
use @mpfr_check_range[I32](parg0: SMPFr, parg1: I32, parg2: I32)
use @mpfr_init2[None](parg0: SMPFr, parg1: ILong)
use @mpfr_init[None](parg0: SMPFr)
use @mpfr_clear[None](parg0: SMPFr)
use @mpfr_inits2[None](parg0: I64, parg1: SMPFr, ...)
use @mpfr_inits[None](parg0: SMPFr, ...)
use @mpfr_clears[None](parg0: SMPFr, ...)
use @mpfr_prec_round[I32](parg0: SMPFr, parg1: ILong, parg2: I32)
use @mpfr_can_round[I32](parg0: SMPFr, parg1: I64, parg2: I32, parg3: I32, parg4: ILong)
use @mpfr_min_prec[ILong](parg0: SMPFr)
use @mpfr_get_exp[I64](parg0: SMPFr)
use @mpfr_set_exp[I32](parg0: SMPFr, parg1: I64)
use @mpfr_get_prec[ILong](parg0: SMPFr)
use @mpfr_set_prec[None](parg0: SMPFr, parg1: ILong)
use @mpfr_set_prec_raw[None](parg0: SMPFr, parg1: ILong)
use @mpfr_set_default_prec[None](parg0: ILong)
use @mpfr_get_default_prec[ILong]()
use @mpfr_set_d[I32](parg0: SMPFr, parg1: F64, parg2: I32)
use @mpfr_set_flt[I32](parg0: SMPFr, parg1: F32, parg2: I32)
// use @mpfr_set_ld[I32](parg0: SMPFr, parg1: F128, parg2: I32)
use @mpfr_set_z[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_set_z_2exp[I32](parg0: SMPFr, parg1: SMPFr, parg2: I64, parg3: I32)
use @mpfr_set_nan[None](parg0: SMPFr)
use @mpfr_set_inf[None](parg0: SMPFr, parg1: I32)
use @mpfr_set_zero[None](parg0: SMPFr, parg1: I32)
use @mpfr_set_f[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_cmp_f[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_get_f[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_set_si[I32](parg0: SMPFr, parg1: ILong, parg2: I32)
use @mpfr_set_ui[I32](parg0: SMPFr, parg1: ULong, parg2: I32)
use @__gmpfr_set_sj[I32](parg0: SMPFr, parg1: ISize, parg2: I32)
use @__gmpfr_set_uj[I32](parg0: SMPFr, parg1: USize, parg2: I32)
use @mpfr_set_si_2exp[I32](parg0: SMPFr, parg1: ILong, parg2: I64, parg3: I32)
use @mpfr_set_ui_2exp[I32](parg0: SMPFr, parg1: ULong, parg2: I64, parg3: I32)
use @mpfr_set_q[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_mul_q[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_div_q[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_add_q[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_sub_q[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_cmp_q[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_get_q[None](q: SMPFr, f: SMPFr)
use @mpfr_set_str[I32](parg0: SMPFr, parg1: Pointer[U8] tag, parg2: I32, parg3: I32)
use @mpfr_init_set_str[I32](parg0: SMPFr, parg1: Pointer[U8] tag, parg2: I32, parg3: I32)
use @mpfr_set4[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32, parg3: I32)
use @mpfr_abs[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_set[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_neg[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_signbit[I32](parg0: SMPFr)
use @mpfr_setsign[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32, parg3: I32)
use @mpfr_copysign[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_get_z_2exp[I64](parg0: SMPFr, parg1: SMPFr)
use @mpfr_get_flt[F32](parg0: SMPFr, parg1: I32)
use @mpfr_get_d[F64](parg0: SMPFr, parg1: I32)
// use @mpfr_get_ld[F128](parg0: SMPFr, parg1: I32)
use @mpfr_get_d1[F64](parg0: SMPFr)
use @mpfr_get_d_2exp[F64](parg0: Pointer[I64] tag, parg1: SMPFr, parg2: I32)
// use @mpfr_get_ld_2exp[F128](parg0: Pointer[I64] tag, parg1: SMPFr, parg2: I32)
use @mpfr_frexp[I32](parg0: Pointer[I64] tag, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_get_si[ILong](parg0: SMPFr, parg1: I32)
use @mpfr_get_ui[ULong](parg0: SMPFr, parg1: I32)
use @__gmpfr_mpfr_get_sj[ISize](parg0: SMPFr, parg1: I32)
use @__gmpfr_mpfr_get_uj[USize](parg0: SMPFr, parg1: I32)
use @mpfr_get_str_ndigits[USize](parg0: I32, parg1: ILong)
use @mpfr_get_str[Pointer[U8]](parg0: Pointer[U8] tag, parg1: Pointer[I64] tag, parg2: I32, parg3: USize, parg4: SMPFr, parg5: I32)
use @mpfr_get_z[I32](z: SMPFr, f: SMPFr, parg2: I32)
use @mpfr_free_str[None](parg0: Pointer[U8] tag)
use @mpfr_urandom[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_grandom[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_nrandom[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_erandom[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_urandomb[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_nextabove[None](parg0: SMPFr)
use @mpfr_nextbelow[None](parg0: SMPFr)
use @mpfr_nexttoward[None](parg0: SMPFr, parg1: SMPFr)
use @mpfr_printf[I32](parg0: Pointer[U8] tag, ...)
use @mpfr_asprintf[I32](parg0: Pointer[Pointer[U8]] tag, parg1: Pointer[U8] tag, ...)
use @mpfr_sprintf[I32](parg0: Pointer[U8] tag, parg1: Pointer[U8] tag, ...)
use @mpfr_snprintf[I32](parg0: Pointer[U8] tag, parg1: U64, parg2: Pointer[U8] tag, ...)
use @mpfr_pow[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_pow_si[I32](parg0: SMPFr, parg1: SMPFr, parg2: ILong, parg3: I32)
use @mpfr_pow_ui[I32](parg0: SMPFr, parg1: SMPFr, parg2: ULong, parg3: I32)
use @mpfr_ui_pow_ui[I32](parg0: SMPFr, parg1: ULong, parg2: ULong, parg3: I32)
use @mpfr_ui_pow[I32](parg0: SMPFr, parg1: ULong, parg2: SMPFr, parg3: I32)
use @mpfr_pow_z[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_sqrt[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_sqrt_ui[I32](parg0: SMPFr, parg1: ULong, parg2: I32)
use @mpfr_rec_sqrt[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_add[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_sub[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_mul[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_div[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_add_ui[I32](parg0: SMPFr, parg1: SMPFr, parg2: ULong, parg3: I32)
use @mpfr_sub_ui[I32](parg0: SMPFr, parg1: SMPFr, parg2: ULong, parg3: I32)
use @mpfr_ui_sub[I32](parg0: SMPFr, parg1: ULong, parg2: SMPFr, parg3: I32)
use @mpfr_mul_ui[I32](parg0: SMPFr, parg1: SMPFr, parg2: ULong, parg3: I32)
use @mpfr_div_ui[I32](parg0: SMPFr, parg1: SMPFr, parg2: ULong, parg3: I32)
use @mpfr_ui_div[I32](parg0: SMPFr, parg1: ULong, parg2: SMPFr, parg3: I32)
use @mpfr_add_si[I32](parg0: SMPFr, parg1: SMPFr, parg2: ILong, parg3: I32)
use @mpfr_sub_si[I32](parg0: SMPFr, parg1: SMPFr, parg2: ILong, parg3: I32)
use @mpfr_si_sub[I32](parg0: SMPFr, parg1: ILong, parg2: SMPFr, parg3: I32)
use @mpfr_mul_si[I32](parg0: SMPFr, parg1: SMPFr, parg2: ILong, parg3: I32)
use @mpfr_div_si[I32](parg0: SMPFr, parg1: SMPFr, parg2: ILong, parg3: I32)
use @mpfr_si_div[I32](parg0: SMPFr, parg1: ILong, parg2: SMPFr, parg3: I32)
use @mpfr_add_d[I32](parg0: SMPFr, parg1: SMPFr, parg2: F64, parg3: I32)
use @mpfr_sub_d[I32](parg0: SMPFr, parg1: SMPFr, parg2: F64, parg3: I32)
use @mpfr_d_sub[I32](parg0: SMPFr, parg1: F64, parg2: SMPFr, parg3: I32)
use @mpfr_mul_d[I32](parg0: SMPFr, parg1: SMPFr, parg2: F64, parg3: I32)
use @mpfr_div_d[I32](parg0: SMPFr, parg1: SMPFr, parg2: F64, parg3: I32)
use @mpfr_d_div[I32](parg0: SMPFr, parg1: F64, parg2: SMPFr, parg3: I32)
use @mpfr_sqr[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_const_pi[I32](parg0: SMPFr, parg1: I32)
use @mpfr_const_log2[I32](parg0: SMPFr, parg1: I32)
use @mpfr_const_euler[I32](parg0: SMPFr, parg1: I32)
use @mpfr_const_catalan[I32](parg0: SMPFr, parg1: I32)
use @mpfr_agm[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_log[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_log2[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_log10[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_log1p[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_log_ui[I32](parg0: SMPFr, parg1: ULong, parg2: I32)
use @mpfr_exp[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_exp2[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_exp10[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_expm1[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_eint[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_li2[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_cmp[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_cmp3[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_cmp_d[I32](parg0: SMPFr, parg1: F64)
// use @mpfr_cmp_ld[I32](parg0: SMPFr, parg1: F128)
use @mpfr_cmp_ui[I32](parg0: SMPFr, parg1: ULong)
use @mpfr_cmp_si[I32](parg0: SMPFr, parg1: ILong)
use @mpfr_cmp_ui_2exp[I32](parg0: SMPFr, parg1: ULong, parg2: I64)
use @mpfr_cmp_si_2exp[I32](parg0: SMPFr, parg1: ILong, parg2: I64)
use @mpfr_cmpabs[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_cmpabs_ui[I32](parg0: SMPFr, parg1: ULong)
use @mpfr_reldiff[None](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_eq[I32](parg0: SMPFr, parg1: SMPFr, parg2: ULong)
use @mpfr_sgn[I32](parg0: SMPFr)
use @mpfr_mul_2exp[I32](parg0: SMPFr, parg1: SMPFr, parg2: U64, parg3: I32)
use @mpfr_div_2exp[I32](parg0: SMPFr, parg1: SMPFr, parg2: U64, parg3: I32)
use @mpfr_mul_2ui[I32](parg0: SMPFr, parg1: SMPFr, parg2: ULong, parg3: I32)
use @mpfr_div_2ui[I32](parg0: SMPFr, parg1: SMPFr, parg2: ULong, parg3: I32)
use @mpfr_mul_2si[I32](parg0: SMPFr, parg1: SMPFr, parg2: ILong, parg3: I32)
use @mpfr_div_2si[I32](parg0: SMPFr, parg1: SMPFr, parg2: ILong, parg3: I32)
use @mpfr_rint[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_roundeven[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_round[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_trunc[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_ceil[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_floor[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_rint_roundeven[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_rint_round[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_rint_trunc[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_rint_ceil[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_rint_floor[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_frac[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_modf[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_remquo[I32](parg0: SMPFr, parg1: Pointer[I64] tag, parg2: SMPFr, parg3: SMPFr, parg4: I32)
use @mpfr_remainder[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_fmod[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_fmodquo[I32](parg0: SMPFr, parg1: Pointer[I64] tag, parg2: SMPFr, parg3: SMPFr, parg4: I32)
use @mpfr_fits_ulong_p[I32](parg0: SMPFr, parg1: I32)
use @mpfr_fits_slong_p[I32](parg0: SMPFr, parg1: I32)
use @mpfr_fits_uint_p[I32](parg0: SMPFr, parg1: I32)
use @mpfr_fits_sint_p[I32](parg0: SMPFr, parg1: I32)
use @mpfr_fits_ushort_p[I32](parg0: SMPFr, parg1: I32)
use @mpfr_fits_sshort_p[I32](parg0: SMPFr, parg1: I32)
use @mpfr_fits_uintmax_p[I32](parg0: SMPFr, parg1: I32)
use @mpfr_fits_intmax_p[I32](parg0: SMPFr, parg1: I32)
use @mpfr_extract[None](parg0: SMPFr, parg1: SMPFr, parg2: U32)
use @mpfr_swap[None](parg0: SMPFr, parg1: SMPFr)
use @mpfr_dump[None](parg0: SMPFr)
use @mpfr_nan_p[I32](parg0: SMPFr)
use @mpfr_inf_p[I32](parg0: SMPFr)
use @mpfr_number_p[I32](parg0: SMPFr)
use @mpfr_integer_p[I32](parg0: SMPFr)
use @mpfr_zero_p[I32](parg0: SMPFr)
use @mpfr_regular_p[I32](parg0: SMPFr)
use @mpfr_greater_p[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_greaterequal_p[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_less_p[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_lessequal_p[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_lessgreater_p[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_equal_p[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_unordered_p[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_atanh[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_acosh[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_asinh[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_cosh[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_sinh[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_tanh[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_sinh_cosh[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_sech[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_csch[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_coth[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_acos[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_asin[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_atan[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_sin[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_sin_cos[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_cos[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_tan[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_atan2[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_sec[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_csc[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_cot[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_hypot[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_erf[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_erfc[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_cbrt[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_root[I32](parg0: SMPFr, parg1: SMPFr, parg2: ULong, parg3: I32)
use @mpfr_rootn_ui[I32](parg0: SMPFr, parg1: SMPFr, parg2: ULong, parg3: I32)
use @mpfr_gamma[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_gamma_inc[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_beta[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_lngamma[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_lgamma[I32](parg0: SMPFr, parg1: Pointer[I32] tag, parg2: SMPFr, parg3: I32)
use @mpfr_digamma[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_zeta[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_zeta_ui[I32](parg0: SMPFr, parg1: ULong, parg2: I32)
use @mpfr_fac_ui[I32](parg0: SMPFr, parg1: ULong, parg2: I32)
use @mpfr_j0[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_j1[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_jn[I32](parg0: SMPFr, parg1: ILong, parg2: SMPFr, parg3: I32)
use @mpfr_y0[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_y1[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_yn[I32](parg0: SMPFr, parg1: ILong, parg2: SMPFr, parg3: I32)
use @mpfr_ai[I32](parg0: SMPFr, parg1: SMPFr, parg2: I32)
use @mpfr_min[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_max[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_dim[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_mul_z[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_div_z[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_add_z[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_sub_z[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_z_sub[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: I32)
use @mpfr_cmp_z[I32](parg0: SMPFr, parg1: SMPFr)
use @mpfr_fma[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: SMPFr, parg4: I32)
use @mpfr_fms[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: SMPFr, parg4: I32)
use @mpfr_fmma[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: SMPFr, parg4: SMPFr, parg5: I32)
use @mpfr_fmms[I32](parg0: SMPFr, parg1: SMPFr, parg2: SMPFr, parg3: SMPFr, parg4: SMPFr, parg5: I32)
use @mpfr_sum[I32](parg0: SMPFr, parg1: Pointer[SMPFr] tag, parg2: USize, parg3: I32)
use @mpfr_dot[I32](parg0: SMPFr, parg1: Pointer[SMPFr] tag, parg2: Pointer[SMPFr] tag, parg3: USize, parg4: I32)
use @mpfr_free_cache[None]()
use @mpfr_free_cache2[None](parg0: I32)
use @mpfr_free_pool[None]()
use @mpfr_mp_memory_cleanup[I32]()
use @mpfr_subnormalize[I32](parg0: SMPFr, parg1: I32, parg2: I32)
// use @mpfr_strtofr[I32](parg0: SMPFr, parg1: Pointer[U8] tag, parg2: Pointer[Pointer[U8]] tag, parg3: I32, parg4: I32)
use @mpfr_round_nearest_away_begin[None](parg0: SMPFr)
use @mpfr_round_nearest_away_end[I32](parg0: SMPFr, parg1: I32)
use @mpfr_custom_get_size[USize](parg0: ILong)
use @mpfr_custom_init[None](parg0: Pointer[None] tag, parg1: ILong)
use @mpfr_custom_get_significand[Pointer[None]](parg0: SMPFr)
use @mpfr_custom_get_exp[I64](parg0: SMPFr)
use @mpfr_custom_move[None](parg0: SMPFr, parg1: Pointer[None] tag)
use @mpfr_custom_init_set[None](parg0: SMPFr, parg1: I32, parg2: I64, parg3: ILong, parg4: Pointer[None] tag)
use @mpfr_custom_get_kind[I32](parg0: SMPFr)
use @mpfr_total_order_p[I32](parg0: SMPFr, parg1: SMPFr)


struct val SMPFr
  """
  The struct representing a float in MPFR.
  """
  var _mpfr_prec: ILong = 0
  var _mpfr_sign: I32 = 0
  var _mpfr_exp: I64 = 0
  var _mpfr_d: Pointer[ULong] = Pointer[ULong]


/* TODO DELETE
struct val SExp
  """
  The struct used to read exponent values
  """
  var exp: I64 = 0
*/

