"""
Tests for mathx package.
"""

use "collections"
use "random"

use "../mathx"
use "../pony_testx"

actor Main is TestList
  new create(env: Env) =>
    PonyTest(env, this)

  fun tag tests(test: PonyTest) =>
    // Platform limits
    test(_TestFLimits[F32])
    test(_TestFLimits[F64])
    test(_TestFLimitsF32Specific)
    test(_TestFLimitsF64Specific)

    // Primes
    test(_TestPrimeTest)
    test(_TestPrimeTestExtended)
    test(_TestNextPrime)
    test(_TestPrimeFactorsStatic)
    test(_TestPrimeFactorsRandom)
    test(_TestPrimeIterator)
    test(_TestCoprime)
    test(_TestProbablyPrime)
    test(_TestProbablyPrimeEdgeCases)
    test(_TestPrimeFactorsPerf)
    test(_TestPrimeFactorsUnique)
    test(_TestEulerTotient)
    test(_TestRadical)
    test(_TestIsSquarefree)
    test(_TestPrevPrime)
    test(_TestPrimeSieve)
    test(_TestSegmentedSieve)

    // Modular arithmetic
    test(_TestGCDLCM)
    test(_TestModularInverse)

    // Complex numbers
    test(_TestComplexAdd[F32])
    test(_TestComplexSub[F32])
    test(_TestComplexMul[F32])
    test(_TestComplexDiv[F32])
    test(_TestComplexAbs[F32])
    test(_TestComplexSqrt[F32])
    test(_TestComplexPow[F32])
    test(_TestComplexMisc[F32])
    test(_TestComplexTrigo[F32])
    test(_TestComplexLog[F32])
    test(_TestComplexIdentities[F32])
    test(_TestComplexRandom[F32, U32])
    test(_TestComplexArg[F32])
    test(_TestComplexExp[F32])
    test(_TestComplexCPow[F32])
    test(_TestComplexEdge[F32])
    test(_TestComplexPolar[F32])
    test(_TestComplexPowf[F32])
    test(_TestComplexLogBases[F32])
    test(_TestComplexInverseTrig[F32])
    test(_TestComplexInverseHyp[F32])
    test(_TestComplexAdd[F64])
    test(_TestComplexSub[F64])
    test(_TestComplexMul[F64])
    test(_TestComplexDiv[F64])
    test(_TestComplexAbs[F64])
    test(_TestComplexSqrt[F64])
    test(_TestComplexPow[F64])
    test(_TestComplexMisc[F64])
    test(_TestComplexTrigo[F64])
    test(_TestComplexLog[F64])
    test(_TestComplexIdentities[F64])
    test(_TestComplexRandom[F64, U64])
    test(_TestComplexArg[F64])
    test(_TestComplexExp[F64])
    test(_TestComplexCPow[F64])
    test(_TestComplexEdge[F64])
    test(_TestComplexPolar[F64])
    test(_TestComplexPowf[F64])
    test(_TestComplexLogBases[F64])
    test(_TestComplexInverseTrig[F64])
    test(_TestComplexInverseHyp[F64])
    test(_TestComplexFromString[F32])
    test(_TestComplexFromString[F64])

    // Miscellaneous functions for unsigned integers
    test(_TestUnsignedComplementPow[U8])
    test(_TestUnsignedComplementPow[U16])
    test(_TestUnsignedComplementPow[U32])
    test(_TestUnsignedComplementPow[U64])
    test(_TestUnsignedComplementPowPartial[U8])
    test(_TestUnsignedComplementPowPartial[U16])
    test(_TestUnsignedComplementPowPartial[U32])
    test(_TestUnsignedComplementPowPartial[U64])
    test(_TestUnsignedComplementLog2[U8])
    test(_TestUnsignedComplementLog2[U16])
    test(_TestUnsignedComplementLog2[U32])
    test(_TestUnsignedComplementLog2[U64])
    test(_TestUnsignedComplementHamming[U8])
    test(_TestUnsignedComplementHamming[U16])
    test(_TestUnsignedComplementHamming[U32])
    test(_TestUnsignedComplementHamming[U64])
    test(_TestUnsignedComplementFloorLog2[U8])
    test(_TestUnsignedComplementFloorLog2[U16])
    test(_TestUnsignedComplementFloorLog2[U32])
    test(_TestUnsignedComplementFloorLog2[U64])
    test(_TestUnsignedComplementIsPowerOfTwo[U8])
    test(_TestUnsignedComplementIsPowerOfTwo[U16])
    test(_TestUnsignedComplementIsPowerOfTwo[U32])
    test(_TestUnsignedComplementIsPowerOfTwo[U64])
    test(_TestUnsignedComplementNextPow2[U8])
    test(_TestUnsignedComplementNextPow2[U16])
    test(_TestUnsignedComplementNextPow2[U32])
    test(_TestUnsignedComplementNextPow2[U64])
    test(_TestUnsignedComplementIsqrt[U8])
    test(_TestUnsignedComplementIsqrt[U16])
    test(_TestUnsignedComplementIsqrt[U32])
    test(_TestUnsignedComplementIsqrt[U64])
    test(_TestUnsignedComplementParity[U8])
    test(_TestUnsignedComplementParity[U16])
    test(_TestUnsignedComplementParity[U32])
    test(_TestUnsignedComplementParity[U64])
    test(_TestUnsignedComplementIlog[U8])
    test(_TestUnsignedComplementIlog[U16])
    test(_TestUnsignedComplementIlog[U32])
    test(_TestUnsignedComplementIlog[U64])

    // FFT: Fast Fourier Transform
    test(_TestFFT[F64])
    test(_TestFFT[F32])
    test(_TestFFTUnsafe[F64])
    test(_TestFFTUnsafe[F32])
    test(_TestFFT2[F64])
    test(_TestFFT2[F32])
    test(_TestFFTComplex[F64])
    test(_TestFFTComplex[F32])
    test(_TestFFTReal[F64])
    test(_TestFFTReal[F32])
    test(_TestFFTConvolution[F64])
    test(_TestFFTConvolution[F32])
    test(_TestFFTBluestein[F64])
    test(_TestFFTBluestein[F32])

    // Complex format
    test(_TestComplexFormatCartesian[F32])
    test(_TestComplexFormatPolar[F32])
    test(_TestComplexFormatWidth[F32])
    test(_TestComplexFormatCartesian[F64])
    test(_TestComplexFormatPolar[F64])
    test(_TestComplexFormatWidth[F64])
