"""
Tests for bignum package.
"""

use "collections"
use "random"

use "../bignum"
use "../mathx"
use "../pony_testx"

actor Main is TestList
  new create(env: Env) =>
    PonyTest(env, this)

  fun tag tests(test: PonyTest) =>
    // BigReal[T] generic interface tests (against MPFloat)
    test(_TestBigRealMPFloatPredicates)
    test(_TestBigRealMPFloatComparisons)
    test(_TestBigRealMPFloatArithmetic)
    test(_TestBigRealMPFloatRoots)
    test(_TestBigRealMPFloatMinMax)
    test(_TestBigRealMPFloatRounding)
    test(_TestBigRealMPFloatLogExp)
    test(_TestBigRealMPFloatTrig)
    test(_TestBigRealMPFloatInverseTrig)
    test(_TestBigRealMPFloatHyp)
    test(_TestBigRealMPFloatConversions)

    // MPFloat — pure Pony arbitrary-precision float
    test(_TestMPFloatNewCreate)
    test(_TestMPFloatNewSpecial)
    test(_TestMPFloatFromF32)
    test(_TestMPFloatFromF64)
    test(_TestMPFloatFromULong)
    test(_TestMPFloatFromStringSpecial)
    test(_TestMPFloatFromStringDecimal)
    test(_TestMPFloatNewString)
    test(_TestMPFloatExactString)
    test(_TestMPFloatExactStringExtreme)
    test(_TestMPFloatExactStringLength)
    test(_TestMPFloatSign)
    test(_TestMPFloatNeg)
    test(_TestMPFloatAdd)
    test(_TestMPFloatSub)
    test(_TestMPFloatMul)
    test(_TestMPFloatInv)
    test(_TestMPFloatDiv)
    test(_TestMPFloatSqrt)
    test(_TestMPFloatCmp)
    test(_TestMPFloatFromMPInt)
    test(_TestMPFloatDivRem)
    test(_TestMPFloatRounding)
    test(_TestMPFloatIsInteger)
    test(_TestMPFloatLn)
    test(_TestMPFloatExp)
    test(_TestMPFloatLog2)
    test(_TestMPFloatLog10)
    test(_TestMPFloatExp2)
    test(_TestMPFloatPowi)
    test(_TestMPFloatPow)
    test(_TestMPFloatHighPrec)
    test(_TestMPFloatTrig)
    test(_TestMPFloatHyp)
    test(_TestMPFloatUnsafeIntConversions)
    test(_TestMPFloatI8)
    test(_TestMPFloatI16)
    test(_TestMPFloatI32)
    test(_TestMPFloatI64)
    test(_TestMPFloatI128)
    test(_TestMPFloatE)
    test(_TestMPFloatConversions)
    test(_TestMPFloatU8)
    test(_TestMPFloatU16)
    test(_TestMPFloatU32)
    test(_TestMPFloatU64)
    test(_TestMPFloatU128)
    test(_TestMPFloatFormatDefault)
    test(_TestMPFloatFormatE)
    test(_TestMPFloatFormatF)
    test(_TestMPFloatFormatG)
    test(_TestMPFloatFormatPct)
    test(_TestMPFloatFormatIntCodes)
    test(_TestMPFloatFormatWidth)
    test(_TestMPFloatFormatSpecial)
    test(_TestMPFloatInverseTrig)
    test(_TestMPFloatInverseHyp)
    test(_TestMPFloatCbrtRootn)
    test(_TestMPFloatMinMaxNext)
    test(_TestMPFloatFormatInFormat)

    // MPInt — arbitrary-precision integers
    test(_TestMPIntCreate)
    test(_TestMPIntFromILong)
    test(_TestMPIntComparisons)
    test(_TestMPIntAbsComparisons)
    test(_TestMPIntConversionILong)
    test(_TestMPIntMiscellaneous)
    test(_TestMPIntArithmetic)
    test(_TestMPIntKaratsuba)
    test(_TestMPIntFastMultiplication)
    test(_TestMPIntFastMultiplicationLarge)
    test(_TestMPIntMultiplicationComparison)
    test(_TestMPIntMultiplicationEdgeCases)
    test(_TestMPIntTrait)
    test(_TestMPIntShift)
    test(_TestMPIntBitwise)
    test(_TestMPIntSign)
    test(_TestMPIntBitAccess)
    test(_TestMPIntPow)
    test(_TestMPIntPredicates)
    test(_TestMPIntHash)
    test(_TestMPIntCarry)
    test(_TestMPIntPartialOps)
    test(_TestMPIntUnsafeArith)
    test(_TestMPIntConversions)
    test(_TestMPIntShiftAlias)
    test(_TestMPIntPowEdge)
    test(_TestMPIntFromMPFloat)
    test(_TestMPIntKaratsubaAsymmetric)
    test(_TestMPIntFromStringLargeExponent)
    test(_TestMPIntFormatDefault)
    test(_TestMPIntFormatBases)
    test(_TestMPIntFormatWidth)
    test(_TestMPIntFormatGrouping)
    test(_TestMPIntFormatPrecision)
    test(_TestMPIntDivision)
    test(_TestMPIntFldMod)
    test(_TestMPIntPopcount)
    test(_TestMPIntBytewidth)
    test(_TestMPIntMathFactorial)

    // MPFContext — precision/rounding context
    test(_TestMPFContextCreate)
    test(_TestMPFContextWorkingBytes)

    // Modular arithmetic with MPInt
    test(_TestModularMPIntBasic)
    test(_TestModularMPIntBig)

    // Integration tests (excluded from normal runs via --exclude=integration)
    test(_TestMPFloatPi1000Machin)
    test(_TestMPFloatPi1000BBP)
    test(_TestMPFloatPi1000Chudnovsky)
